"""Executor node: dispatches the current plan step to the appropriate tool."""

from datetime import datetime, timezone
from typing import Any

from src.worker.config import OSTICKET_STAFF_PASS, OSTICKET_STAFF_USER
from src.worker.security import redact_sensitive_data
from src.worker.state import ActionRecord, TaskWorkerState
from src.worker.tools.registry import ToolRegistry, ToolResult


def _resolve_params(params: dict[str, Any], state: TaskWorkerState) -> dict[str, Any]:
    """Substitute template variables from state memory or previous action output.

    Allows the planner to chain steps dynamically:
      {last_output}: the output text of the immediately preceding action
      {support_response}: the resolution generated by the support_agent tool
      {ticket_reply_status}: dynamic ticket status (Resolved if confirmed, Open if troubleshooting)
      {staff_user} / {staff_pass}: verified osTicket login credentials (ostadmin / Admin1)
      {<key>}: any key extracted and saved into state.memory
    """
    resolved = dict(params)
    last_output = state.actions[-1].output if state.actions else ""

    last_support = ""
    for act in reversed(state.actions):
        if act.tool == "support_agent" and act.success and act.output:
            last_support = act.output
            break

    is_resolved = state.memory.get("is_resolved")
    ticket_reply_status = state.memory.get("ticket_reply_status")

    task_goal_text = f"{state.task or ''} {state.goal or ''}".lower()
    is_explicit_resolve_task = any(
        k in task_goal_text
        for k in ("resolve ticket", "closing reply", "close ticket", "mark resolved", "mark as resolved", "resolved with")
    )
    is_resolve_intent = (
        is_explicit_resolve_task
        or is_resolved is True
        or ticket_reply_status == "Resolved"
    )

    for k, v in list(resolved.items()):
        if isinstance(v, str):
            val = v
            if "{last_output}" in val:
                val = val.replace("{last_output}", last_output)
            if "{support_response}" in val or "{response}" in val or "{reply}" in val:
                repl = last_support or last_output
                val = val.replace("{support_response}", repl).replace("{response}", repl).replace("{reply}", repl)
            if "{ticket_reply_status}" in val:
                repl_status = "Resolved" if (is_explicit_resolve_task or is_resolved is True) else (ticket_reply_status or "Open")
                val = val.replace("{ticket_reply_status}", repl_status)
            if "{staff_user}" in val or "{admin_user}" in val:
                val = val.replace("{staff_user}", OSTICKET_STAFF_USER).replace("{admin_user}", OSTICKET_STAFF_USER)
            if "{staff_pass}" in val or "{admin_pass}" in val:
                val = val.replace("{staff_pass}", OSTICKET_STAFF_PASS).replace("{admin_pass}", OSTICKET_STAFF_PASS)
            for mem_k, mem_v in state.memory.items():
                target = f"{{{mem_k}}}"
                if target in val:
                    val = val.replace(target, str(mem_v))
            resolved[k] = val

    # If action is "type" and text is empty or a placeholder, auto-inject the support agent response or closing reply
    selector_str = str(resolved.get("selector", "")).lower()
    is_reply_field = any(k in selector_str for k in ("contenteditable", "redactor", "response", "#reply"))

    if resolved.get("action") == "type":
        current_text = str(resolved.get("text", "")).strip()
        if not current_text or current_text in ("...", "{text}", "{support_response}"):
            if last_support and not (is_explicit_resolve_task and not is_resolved):
                resolved["text"] = last_support
            elif is_reply_field and is_resolve_intent:
                resolved["text"] = (
                    "You're very welcome! We're glad to hear that resolved your issue. "
                    "If you ever need help with anything else in the future, don't hesitate to reach out. Happy listening! 🎵"
                )
            elif last_support:
                resolved["text"] = last_support

    # Enforce verified osTicket staff admin credentials on login fields
    selector_str = str(resolved.get("selector", "")).lower()
    if resolved.get("action") in ("type", "fill"):
        # Login username field (input[name="userid"], input[name='userid'], #name, #userid)
        if (
            "userid" in selector_str
            or selector_str in ("#name", "#userid", "input#name", "input#userid")
        ) and not any(k in selector_str for k in ("query", "search", "filter")):
            resolved["text"] = OSTICKET_STAFF_USER
        # Login password field (input[name="passwd"], input[name='passwd'], #pass, #passwd)
        elif (
            "passwd" in selector_str
            or selector_str in ("#pass", "#passwd", "input#pass", "input#passwd")
        ):
            if "text" in resolved or "value" in resolved:
                resolved["text"] = OSTICKET_STAFF_PASS

    # Guard: if selecting ticket reply status in osTicket
    if resolved.get("action") == "select" and "reply_status_id" in str(resolved.get("selector", "")):
        step_val = str(resolved.get("value", "")).strip()
        if is_explicit_resolve_task or is_resolved is True or ticket_reply_status == "Resolved":
            resolved["value"] = "Resolved"
        elif is_resolved is False:
            resolved["value"] = ticket_reply_status or "Open"
        elif step_val.lower() in ("resolved", "resolve", "2", "closed"):
            resolved["value"] = "Resolved"
        else:
            resolved["value"] = "Open"

    return resolved



async def executor_node(
    state: TaskWorkerState,
    *,
    registry: ToolRegistry,
) -> dict[str, Any]:
    """Execute the current plan step using the tool registry."""
    if state.step_index >= len(state.plan):
        return {"status": "verifying"}

    step = state.plan[state.step_index]

    # Mark step as running
    updated_plan = list(state.plan)
    updated_plan[state.step_index] = step.model_copy(update={"status": "running"})

    resolved_params = _resolve_params(step.params, state)
    result: ToolResult = await registry.run(step.tool, resolved_params)

    record = ActionRecord(
        step_index=step.index,
        tool=step.tool,
        params=redact_sensitive_data(resolved_params),
        output=result.output,
        error=result.error,
        success=result.success,
        timestamp=datetime.now(timezone.utc),
        screenshot=result.screenshot,
    )

    # Collect evidence screenshots
    evidence = list(state.evidence)
    if result.screenshot:
        evidence.append(result.screenshot)

    memory = dict(state.memory)
    if getattr(result, "metadata", None):
        memory.update(result.metadata)

    return {
        "plan": updated_plan,
        "actions": [*state.actions, record],
        "evidence": evidence,
        "memory": memory,
    }

